TRUNCATE SCHEMA PUBLIC AND COMMIT;
ALTER SEQUENCE global_seq RESTART WITH 100000;
DROP FUNCTION GET_START_DATE;
DROP FUNCTION GET_END_DATE;

CREATE FUNCTION GET_START_DATE() RETURNS DATETIME
    RETURN SYSDATE;

CREATE FUNCTION GET_END_DATE() RETURNS DATETIME
    RETURN SYSDATE - 1 DAY;

INSERT INTO PUBLIC.USERS (ID, NAME, EMAIL, ENABLED, PASSWORD, USER_ID)
VALUES (NEXT VALUE FOR global_seq, 'ADMIN_TEST', 'admin@mail.ru', true, '1',
        CURRENT VALUE FOR global_seq);
INSERT INTO PUBLIC.USERS (ID, NAME, EMAIL, ENABLED, PASSWORD, USER_ID)
VALUES (NEXT VALUE FOR global_seq, 'USER_TEST', 'user@mail.ru', true, '1',
        CURRENT VALUE FOR global_seq - 1);

INSERT INTO PUBLIC.USER_ROLES (USER_ID, ROLE)
VALUES (100000, 'ADMIN');
INSERT INTO PUBLIC.USER_ROLES (USER_ID, ROLE)
VALUES (100001, 'USER');

INSERT INTO PUBLIC.RESTAURANTS (ID, NAME, USER_ID)
VALUES (NEXT VALUE FOR global_seq, 'RESTAURANT-TEST-1', 100000);
INSERT INTO PUBLIC.RESTAURANTS (ID, NAME, USER_ID)
VALUES (NEXT VALUE FOR global_seq, 'RESTAURANT-TEST-2', 100000);
INSERT INTO PUBLIC.RESTAURANTS (ID, NAME, USER_ID)
VALUES (NEXT VALUE FOR global_seq, 'RESTAURANT-TEST-3', 100000);
INSERT INTO PUBLIC.RESTAURANTS (ID, NAME, USER_ID, START_DATE, END_DATE, STATUS)
VALUES (NEXT VALUE FOR global_seq, 'DELETED-RESTAURANT-TEST', 100000,
        GET_START_DATE(), SYSDATE, 'ACTIVE');
INSERT INTO PUBLIC.RESTAURANTS (ID, NAME, USER_ID, START_DATE, END_DATE, STATUS)
VALUES (NEXT VALUE FOR global_seq - 1, 'DELETED-RESTAURANT-TEST', 100000,
        SYSDATE, GET_END_DATE(), 'DELETED');

-- New today menu
INSERT INTO PUBLIC.MENUS (ID, MENU_DATE, USER_ID, RESTAURANT_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, 100000, 100002);
-- Yesterday menu
INSERT INTO PUBLIC.MENUS (ID, MENU_DATE, USER_ID, RESTAURANT_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE - 1 DAY, 100000, 100003);
-- Deleted menu
INSERT INTO PUBLIC.MENUS (ID, MENU_DATE, USER_ID, RESTAURANT_ID, START_DATE, END_DATE, STATUS)
VALUES (NEXT VALUE FOR global_seq, GET_START_DATE(), 100000, 100004, GET_START_DATE(), SYSDATE, 'ACTIVE');
INSERT INTO PUBLIC.MENUS (ID, MENU_DATE, USER_ID, RESTAURANT_ID, START_DATE, END_DATE, STATUS)
VALUES (NEXT VALUE FOR global_seq - 1, GET_START_DATE(), 100000, 100004, SYSDATE, GET_END_DATE(), 'ACTIVE');

INSERT INTO PUBLIC.DISHES (ID, NAME, PRICE, USER_ID)
VALUES (NEXT VALUE FOR global_seq, 'DISH-TEST-1', 1.10, 100000);
INSERT INTO PUBLIC.DISHES (ID, NAME, PRICE, USER_ID)
VALUES (NEXT VALUE FOR global_seq, 'DISH-TEST-2', 2.20, 100000);
INSERT INTO PUBLIC.DISHES (ID, NAME, PRICE, USER_ID)
VALUES (NEXT VALUE FOR global_seq, 'DISH-TEST-3', 3.30, 100000);
INSERT INTO PUBLIC.DISHES (ID, NAME, PRICE, USER_ID, START_DATE, END_DATE, STATUS)
VALUES (NEXT VALUE FOR global_seq, 'DISH-DELETE-TEST', 4.40, 100000, GET_START_DATE(), SYSDATE, 'ACTIVE');
INSERT INTO PUBLIC.DISHES (ID, NAME, PRICE, USER_ID, START_DATE, END_DATE, STATUS)
VALUES (NEXT VALUE FOR global_seq, 'DISH-DELETE-TEST', 4.40, 100000, GET_START_DATE(), SYSDATE, 'ACTIVE');

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, DISH_ID)
VALUES (100006, 100009);
INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, DISH_ID)
VALUES (100006, 100010);

INSERT INTO PUBLIC.VOTES (ID, DELETE_DATE, EDIT_DATE, VOTE_DATE, DELETE_USER_ID, USER_ID, RESTAURANT_ID)
VALUES (NEXT VALUE FOR global_seq, null, SYSDATE, SYSDATE, null, 100001, 100002);
INSERT INTO PUBLIC.VOTES (ID, DELETE_DATE, EDIT_DATE, VOTE_DATE, DELETE_USER_ID, USER_ID, RESTAURANT_ID)
VALUES (NEXT VALUE FOR global_seq, null, SYSDATE, SYSDATE, null, 100001, 100003);
COMMIT;