TRUNCATE SCHEMA PUBLIC AND COMMIT;
ALTER SEQUENCE global_seq RESTART WITH 100000;

INSERT INTO PUBLIC.USERS (ID, EDIT_DATE, NAME, EMAIL, ENABLED, PASSWORD, REGISTERED, USER_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, 'ADMIN_TEST', 'admin@mail.ru', true,
        '$2a$10$yhom5huExULX/BhETMKereeEg69hOUy2b/J6.dq8PRyrOLnqaVQK6', SYSDATE,
        CURRENT VALUE FOR global_seq);
INSERT INTO PUBLIC.USERS (ID, EDIT_DATE, NAME, EMAIL, ENABLED, PASSWORD, REGISTERED, USER_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, 'USER_TEST', 'user@mail.ru', true,
        '$2a$10$yhom5huExULX/BhETMKereeEg69hOUy2b/J6.dq8PRyrOLnqaVQK6', SYSDATE,
        CURRENT VALUE FOR global_seq - 1);

INSERT INTO PUBLIC.USER_ROLES (USER_ID, ROLE)
VALUES (100000, 'ADMIN');
INSERT INTO PUBLIC.USER_ROLES (USER_ID, ROLE)
VALUES (100001, 'USER');

INSERT INTO PUBLIC.RESTAURANTS (ID, EDIT_DATE, NAME, USER_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, 'RESTAURANT-TEST-1', 100000);
INSERT INTO PUBLIC.RESTAURANTS (ID, EDIT_DATE, NAME, USER_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, 'RESTAURANT-TEST-2', 100000);
INSERT INTO PUBLIC.RESTAURANTS (ID, EDIT_DATE, NAME, USER_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, 'RESTAURANT-TEST-3', 100000);
INSERT INTO PUBLIC.RESTAURANTS (ID, EDIT_DATE, NAME, USER_ID, DELETE_DATE, DELETE_USER_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, 'DELETED-RESTAURANT-TEST', 100000, SYSDATE, 100000);

INSERT INTO PUBLIC.MENUS (ID, EDIT_DATE, MENU_DATE, USER_ID, RESTAURANT_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, SYSDATE, 100000, 100002);
INSERT INTO PUBLIC.MENUS (ID, EDIT_DATE, MENU_DATE, USER_ID, RESTAURANT_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, SYSDATE - 1 DAY, 100000, 100003);
INSERT INTO PUBLIC.MENUS (ID, EDIT_DATE, MENU_DATE, USER_ID, RESTAURANT_ID, DELETE_DATE, DELETE_USER_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, SYSDATE, 100000, 100004, SYSDATE, 100000);

INSERT INTO PUBLIC.DISHES (ID, EDIT_DATE, NAME, PRICE, USER_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, 'DISH-TEST-1', 1.10, 100000);
INSERT INTO PUBLIC.DISHES (ID, EDIT_DATE, NAME, PRICE, USER_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, 'DISH-TEST-2', 2.20, 100000);
INSERT INTO PUBLIC.DISHES (ID, EDIT_DATE, NAME, PRICE, USER_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, 'DISH-TEST-3', 3.30, 100000);
INSERT INTO PUBLIC.DISHES (ID, EDIT_DATE, NAME, PRICE, USER_ID, DELETE_DATE, DELETE_USER_ID)
VALUES (NEXT VALUE FOR global_seq, SYSDATE, 'DISH-DELETE-TEST', 4.40, 100000, SYSDATE, 100000);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, DISH_ID)
VALUES (100006, 100009);
INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, DISH_ID)
VALUES (100006, 100010);

INSERT INTO PUBLIC.VOTES (ID, DELETE_DATE, EDIT_DATE, VOTE_DATE, DELETE_USER_ID, USER_ID, RESTAURANT_ID)
VALUES (NEXT VALUE FOR global_seq, null, SYSDATE, SYSDATE, null, 100001, 100002);
INSERT INTO PUBLIC.VOTES (ID, DELETE_DATE, EDIT_DATE, VOTE_DATE, DELETE_USER_ID, USER_ID, RESTAURANT_ID)
VALUES (NEXT VALUE FOR global_seq, null, SYSDATE, SYSDATE, null, 100001, 100003);
COMMIT;